from typing import Dict, Any
# from ..state import AgentState
try:
    from ..state import AgentState
except ImportError:
    from langgraph_agent_project.agents.example_agent.state import AgentState


def response_node(state: AgentState) -> Dict[str, Any]:
    '''
    Generates the final response to the user.
    This node is typically called when the agent has gathered all necessary
    information (e.g., after tool use or if it can answer directly).

    Reads: final_output (if already set by thought_node), or current_thought, tool_observation.
    Updates: final_output (if not already set).
    '''
    print("--- Running Response Node ---")

    final_output = state.get("final_output")

    if final_output:
        print(f"Final output already generated by a previous node: {final_output}")
        # No change needed if final_output is already satisfactory.
        # Or, this node could be used to format it or add a concluding remark.
        return {"messages": state.get("messages", []) + [("ai", final_output)]}

    # If final_output is not set, generate it.
    # This might involve an LLM call to synthesize an answer based on thoughts/observations.
    current_thought = state.get("current_thought", "")
    tool_observation = state.get("tool_observation")

    # Mock logic for generating a response:
    if tool_observation:
        generated_response = f"Based on my findings ({tool_observation}), here is your answer."
        print(f"Generated response using tool observation: {generated_response}")
    elif current_thought:
        generated_response = f"My thought process led me to this conclusion: {current_thought}. Therefore, the answer is..."
        print(f"Generated response using current thought: {generated_response}")
    else:
        # Fallback if no clear thought or observation led here (should be handled by graph logic)
        generated_response = "I'm ready to provide an answer, but I need more specific information from my internal state."
        print("Warning: Response node reached without clear input for response generation.")

    # In a real agent, this might be an AIMessage to be added to `messages`
    # and also stored in `final_output` for clarity that this is the end result.
    return {
        "final_output": generated_response,
        "messages": state.get("messages", []) + [("ai", generated_response)]
    }
