from langgraph.graph import StateGraph, END
from typing import Literal

# Assuming AgentState, node functions are accessible
# This structure assumes graph.py is in the same directory as state.py and nodes/
try:
    from .state import AgentState
    from .nodes import (
        thought_node,
        # tool_selection_node, # Optional, depends on agent design
        tool_execution_node,
        response_node,
    )
    # If LLM services or tool registries are needed by nodes,
    # they would typically be initialized elsewhere and passed to the node functions
    # when adding them to the graph, often using functools.partial.
    # For now, nodes have mock/self-contained dependencies or assume global access.
except ImportError:
    # Fallback for different execution context or if structure changes
    print("Error: Could not import AgentState or node functions. Ensure paths are correct.")
    # Define dummy versions for the script to be parsable if imports fail in some contexts
    class AgentState(dict): pass
    def thought_node(state): return {}
    def tool_execution_node(state): return {}
    def response_node(state): return {}
    # END = "__end__" # Already imported from langgraph.graph


# Define the graph workflow
workflow = StateGraph(AgentState)

# Add nodes to the graph
# Nodes take the current state and return a dictionary of updates to the state.
workflow.add_node("thought_node", thought_node)
# workflow.add_node("tool_selection_node", tool_selection_node) # If using this node
workflow.add_node("tool_execution_node", tool_execution_node)
workflow.add_node("response_node", response_node)

# Set the entry point for the graph
workflow.set_entry_point("thought_node")

# Define edges and conditional logic

def should_continue_or_use_tool(state: AgentState) -> Literal["tool_execution_node", "response_node", END]:
    '''
    Decision logic after the thought_node.
    Determines if a tool should be used, if the agent should respond directly,
    or if the process should end.
    '''
    print("--- Conditional Logic: Should Continue or Use Tool? ---")
    if state.get("error_message"):
        print(f"Error detected: {state.get('error_message')}. Ending.")
        return END # Or a dedicated error handling node

    if state.get("final_output") and not state.get("tool_name"): # If thought_node produced a final answer
        print("Decision: Final output generated by thought_node. Proceed to response_node (or END).")
        # If response_node is just for formatting, and thought_node can give final answer.
        # Or, if thought_node sets final_output, it might mean END.
        # Let's assume if thought_node sets final_output, it's the answer.
        return "response_node" # Or directly END if response_node is not needed for thought_node's direct answers

    if state.get("tool_name"):
        print(f"Decision: Tool '{state.get('tool_name')}' selected. Proceed to tool_execution_node.")
        return "tool_execution_node"

    # Fallback or if thought_node didn't set a tool or final_output clearly
    # This condition might need refinement based on how thought_node behaves.
    # If thought_node always sets either a tool or a final_output (or an error), this might not be reached.
    print("Decision: No tool selected, but no final output from thought. Assuming it's time to respond/end.")
    return "response_node" # Or END, depending on desired behavior.


# This edge determines what to do after the 'thought_node'
workflow.add_conditional_edges(
    "thought_node",
    should_continue_or_use_tool,
    {
        "tool_execution_node": "tool_execution_node",
        "response_node": "response_node", # If thought leads to direct response
        END: END,
    },
)

# After tool execution, decide what to do next.
# Typically, go back to thought_node to process tool output, or end if error/done.
def after_tool_execution(state: AgentState) -> Literal["thought_node", END]:
    '''
    Decision logic after the tool_execution_node.
    Usually, this means returning to the thought_node to process the tool's observation.
    '''
    print("--- Conditional Logic: After Tool Execution ---")
    if state.get("error_message") and "Tool execution failed critically" in state.get("error_message", ""): # Example of critical error
        print("Decision: Critical error during tool execution. Ending.")
        return END

    # If tool execution was successful, the observation is in the state.
    # Go back to thought_node to allow the LLM to process this observation.
    print("Decision: Tool executed. Return to thought_node to process observation.")
    return "thought_node"

workflow.add_conditional_edges(
    "tool_execution_node",
    after_tool_execution,
    {
        "thought_node": "thought_node", # Loop back to think about the tool's output
        END: END,
    },
)

# After response_node, the graph should typically end.
workflow.add_edge("response_node", END)


# Compile the graph into a runnable app
# The compiled app can be invoked with input and streams intermediate states.
try:
    agent_graph_app = workflow.compile()
    print("Agent graph compiled successfully.")
except Exception as e:
    print(f"Error compiling agent graph: {e}")
    agent_graph_app = None


# Example of how to run (invoke) the compiled graph (for testing)
if __name__ == "__main__":
    if agent_graph_app:
        print("\n--- Running Compiled Agent Graph Example ---")

        # Initial state for the graph
        # Messages would typically be populated by an orchestrator based on user interaction
        initial_run_state_1 = {
            "input": "What's the weather like in New York today?",
            "messages": [("human", "What's the weather like in New York today?")],
            "scratchpad": [],
            "iterations": 0,
        }

        print(f"\nInvoking with input: '{initial_run_state_1['input']}'")
        # `.stream()` returns an iterator of all state changes
        # For a single final output, you might use `.invoke()`
        try:
            for s_idx, step_output in enumerate(agent_graph_app.stream(initial_run_state_1, {"recursion_limit": 10})):
                # `step_output` is a dictionary where keys are node names and values are the output of that node
                node_name = list(step_output.keys())[0]
                node_output_state = step_output[node_name]
                print(f"--- Step {s_idx + 1}: Node '{node_name}' Output ---")
                # print(f"Full state after node '{node_name}': {node_output_state}") # This can be very verbose
                print(f"  Input: {node_output_state.get('input')}")
                print(f"  Current Thought: {node_output_state.get('current_thought')}")
                print(f"  Tool Name: {node_output_state.get('tool_name')}")
                print(f"  Tool Input: {node_output_state.get('tool_input')}")
                print(f"  Tool Observation: {node_output_state.get('tool_observation')}")
                print(f"  Final Output: {node_output_state.get('final_output')}")
                print(f"  Error Message: {node_output_state.get('error_message')}")
                # print(f"  Messages: {[msg.pretty_repr() if hasattr(msg, 'pretty_repr') else str(msg) for msg in node_output_state.get('messages', [])]}")

            # The final state after the stream is exhausted
            final_state = agent_graph_app.invoke(initial_run_state_1, {"recursion_limit": 10})
            print("\n--- Final State of the Graph ---")
            print(f"  Input: {final_state.get('input')}")
            print(f"  Final Output: {final_state.get('final_output')}")
            print(f"  Messages: {[str(m) for m in final_state.get('messages', [])]}")

        except Exception as run_e:
            print(f"Error running graph: {run_e}")


        # Example 2: Direct answer (mocked by thought_node)
        initial_run_state_2 = {
            "input": "Hello, how are you?",
            "messages": [("human", "Hello, how are you?")],
            "scratchpad": [],
            "iterations": 0,
        }
        print(f"\nInvoking with input: '{initial_run_state_2['input']}' for a direct answer scenario")
        try:
            final_state_2 = agent_graph_app.invoke(initial_run_state_2, {"recursion_limit": 5})
            print("\n--- Final State of the Graph (Direct Answer Scenario) ---")
            print(f"  Input: {final_state_2.get('input')}")
            print(f"  Final Output: {final_state_2.get('final_output')}")
            print(f"  Messages: {[str(m) for m in final_state_2.get('messages', [])]}")
        except Exception as run_e:
            print(f"Error running graph for direct answer: {run_e}")
    else:
        print("Graph compilation failed. Cannot run example.")
