from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder, SystemMessagePromptTemplate, HumanMessagePromptTemplate

# General System Prompt for the Agent
# This prompt defines the agent's persona, overall goal, and how it should behave.
# It often includes placeholders for tool descriptions and formatting instructions.
REACT_SYSTEM_PROMPT_TEMPLATE = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate.from_template(
            """You are a helpful AI assistant. Your goal is to assist the user with their tasks.
You have access to the following tools:

{tool_schemas}

To use a tool, you MUST respond in the following JSON format:
```json
{{
    "thought": "Your reasoning for choosing the tool and how you'll use its output.",
    "tool_name": "tool_name_here",
    "tool_input": {{ "argument_name": "value" }}
}}
```

If you can answer directly without using a tool, or if you have used a tool and now have the answer,
respond to the user directly with your answer. Do not use the JSON format in this case.

If you need to ask the user for clarification, do so directly.

Begin!"""
        ),
        MessagesPlaceholder(variable_name="messages"), # For chat history
        # HumanMessagePromptTemplate.from_template("{input}"), # Input is usually part of messages
    ]
)

# A simpler prompt if the agent is not using a complex ReAct loop or function calling
SIMPLE_AGENT_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful assistant. Answer the user's questions to the best of your ability."),
        MessagesPlaceholder(variable_name="messages"),
        # ("human", "{input}"),
    ]
)

# Prompt for a node that specifically decides whether to use a tool or not
# (if not using OpenAI function calling which has this built-in)
TOOL_DECISION_PROMPT_TEMPLATE = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate.from_template(
            """Given the user's query and the conversation history, decide if using one of the available tools would be beneficial.
Available tools:
{tool_schemas}

User query: {input}
Conversation history:
{chat_history}

Respond with 'yes' if a tool is needed, or 'no' if you can answer directly or if no tool is suitable.
If 'yes', also suggest which tool might be appropriate based on its description, but do not try to use it yet."""
        ),
    ]
)


# Example of a prompt template for formatting tool output for the LLM
TOOL_RESPONSE_FORMATTING_PROMPT_TEMPLATE = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate.from_template(
            "You have used the '{tool_name}' tool and received the following observation: '{tool_observation}'. "
            "Based on this, and the original user query ('{input}'), formulate the next step or the final answer."
            "Consider the ongoing conversation: {chat_history}"
        ),
        MessagesPlaceholder(variable_name="messages") # To allow further interaction based on this
    ]
)


if __name__ == "__main__":
    # Example usage of the ReAct system prompt template
    # (Tool schemas would be dynamically generated by ToolRegistry)
    mock_tool_schemas = [
        {
            "name": "web_search",
            "description": "Searches the web for current information.",
            "parameters": {
                "type": "object",
                "properties": {"query": {"type": "string", "description": "The search query."}},
                "required": ["query"],
            },
        },
        {
            "name": "calculator",
            "description": "Calculates mathematical expressions.",
            "parameters": {
                "type": "object",
                "properties": {"expression": {"type": "string", "description": "The expression to evaluate."}},
                "required": ["expression"],
            },
        },
    ]

    import json
    formatted_tool_schemas = json.dumps(mock_tool_schemas, indent=2)

    # Example messages list
    from langchain_core.messages import HumanMessage, AIMessage
    example_messages = [
        HumanMessage(content="What's the weather in London and what is 2+2?"),
        # AIMessage( # Example of an AI message that would be a tool call
        #     content="",
        #     additional_kwargs={
        #         "tool_calls": [{
        #             "id": "call_123",
        #             "type": "function",
        #             "function": {"name": "web_search", "arguments": '{"query": "weather in London"}'}
        #         }]
        #     }
        # )
    ]

    react_prompt_instance = REACT_SYSTEM_PROMPT_TEMPLATE.format_messages(
        tool_schemas=formatted_tool_schemas,
        messages=example_messages,
        # input="What's the weather in London and what is 2+2?" # Input is part of messages now
    )
    print("--- ReAct System Prompt Example ---")
    for message in react_prompt_instance:
        print(f"Type: {message.type}, Content: {message.content}")
        if message.additional_kwargs:
            print(f"Additional Kwargs: {message.additional_kwargs}")

    print("\n--- Simple Agent Prompt Example ---")
    simple_prompt_instance = SIMPLE_AGENT_PROMPT.format_messages(
        messages=[HumanMessage(content="Hello there!")]
    )
    for message in simple_prompt_instance:
        print(f"Type: {message.type}, Content: {message.content}")
